# Generated by Django 3.1.4 on 2021-01-21 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=30)),
                ('sdep', models.CharField(max_length=30)),
                ('srno', models.FloatField(max_length=30)),
                ('semail', models.EmailField(max_length=30)),
                ('smob', models.IntegerField(max_length=30)),
            ],
        ),
    ]
