# Generated by Django 3.1.4 on 2021-01-21 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ece', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=30)),
                ('sdep', models.CharField(max_length=30)),
                ('srno', models.IntegerField()),
                ('semail', models.EmailField(max_length=30)),
                ('smob', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Stud',
        ),
    ]
