# Generated by Django 3.1.4 on 2021-02-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ece', '0004_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telug', models.IntegerField(max_length=3)),
                ('hindi', models.IntegerField(max_length=3)),
                ('english', models.IntegerField(max_length=3)),
                ('maths', models.IntegerField(max_length=3)),
                ('science', models.IntegerField(max_length=3)),
                ('social', models.IntegerField(max_length=3)),
            ],
        ),
    ]
