# Generated by Django 3.1.4 on 2021-02-08 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ece', '0005_subjects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjects',
            old_name='telug',
            new_name='telugu',
        ),
    ]
