# Generated by Django 3.1.4 on 2021-02-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ece', '0006_auto_20210208_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='fsal',
            field=models.IntegerField(max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='smob',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='english',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='hindi',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='maths',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='science',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='social',
            field=models.IntegerField(max_length=30),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='telugu',
            field=models.IntegerField(),
        ),
    ]
