# Generated by Django 3.1.4 on 2021-02-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ece', '0007_auto_20210216_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='smob',
            field=models.IntegerField(max_length=30),
        ),
    ]
