# Generated by Django 3.1.4 on 2021-01-08 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpSalary',
            fields=[
                ('eno', models.IntegerField(primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=30)),
                ('esal', models.FloatField()),
                ('eaddr', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'empsalary',
            },
        ),
    ]
