# Generated by Django 3.1.1 on 2021-06-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20210601_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.IntegerField(),
        ),
    ]
