# Generated by Django 3.1.1 on 2021-06-03 08:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prfile',
            new_name='Profile',
        ),
    ]
