# Generated by Django 3.1.4 on 2021-03-26 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=125)),
                ('semail', models.EmailField(max_length=254)),
                ('smob', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('sadd', models.CharField(max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='TestMode',
            fields=[
                ('boolean', models.BooleanField(default=True, verbose_name='this is boolean field')),
                ('char', models.CharField(help_text='added help text', max_length=220, unique=True, verbose_name='New name')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('decimal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('email', models.EmailField(max_length=125)),
                ('file', models.FileField(blank=True, upload_to='uploads')),
                ('image', models.ImageField(blank=True, upload_to='uploads')),
                ('integer', models.IntegerField()),
                ('positive_integer', models.PositiveIntegerField()),
                ('slug', models.SlugField(blank=True)),
                ('text', models.TextField()),
                ('url', models.URLField()),
                ('uuid1', models.UUIDField(default=uuid.uuid4)),
                ('uuid2', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_and_time', models.DateTimeField()),
                ('choice', models.CharField(choices=[('one', 'number one'), ('two', 'number two')], max_length=10)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('new_field', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
